import { z } from "zod";

// Generated by tests/live/generate-schemas.ts from a live capture. Required =
// present and non-null in every sample; all values may be null (Garmin returns
// nulls on days without data).

export const responseSchemas: Record<string, z.ZodType> = {
  activities: z
    .array(
      z
        .looseObject({
          activityId: z.number().nullable(),
          activityName: z.string().nullable(),
          startTimeLocal: z.string().nullable(),
          startTimeGMT: z.string().nullable(),
          activityType: z
            .looseObject({
              typeId: z.number().nullable(),
              typeKey: z.string().nullable(),
              parentTypeId: z.number().nullable(),
              isHidden: z.boolean().nullable(),
              restricted: z.boolean().nullable(),
              trimmable: z.boolean().nullable(),
            })
            .nullable(),
          eventType: z
            .looseObject({
              typeId: z.number().nullable(),
              typeKey: z.string().nullable(),
              sortOrder: z.number().nullable(),
            })
            .nullable(),
          isFavorite: z.boolean().nullable(),
          isPR: z.boolean().nullable(),
          isAutoCalcCalories: z.boolean().nullable(),
          isParent: z.boolean().nullable(),
          distance: z.number().nullable(),
          duration: z.number().nullable(),
          elapsedDuration: z.number().nullable(),
          movingDuration: z.number().nullable(),
          averageSpeed: z.number().nullable(),
          maxSpeed: z.number().nullable(),
          hasPolyline: z.boolean().nullable(),
          hasImages: z.boolean().nullable(),
          ownerId: z.number().nullable(),
          ownerDisplayName: z.string().nullable(),
          ownerFullName: z.string().nullable(),
          ownerProfileImageUrlSmall: z.string().nullable(),
          ownerProfileImageUrlMedium: z.string().nullable(),
          ownerProfileImageUrlLarge: z.string().nullable(),
          calories: z.number().nullable(),
          bmrCalories: z.number().nullable(),
          averageHR: z.number().nullable(),
          maxHR: z.number().nullable(),
          averageRunningCadenceInStepsPerMinute: z.number().nullable(),
          maxRunningCadenceInStepsPerMinute: z.number().nullable(),
          steps: z.number().nullable(),
          userRoles: z.array(z.string().nullable()).nullable(),
          privacy: z
            .looseObject({
              typeId: z.number().nullable(),
              typeKey: z.string().nullable(),
            })
            .nullable(),
          userPro: z.boolean().nullable(),
          hasVideo: z.boolean().nullable(),
          isPurposeful: z.boolean().nullable(),
          timeZoneId: z.number().nullable(),
          beginTimestamp: z.number().nullable(),
          sportTypeId: z.number().nullable(),
          avgPower: z.number().nullable(),
          maxPower: z.number().nullable(),
          aerobicTrainingEffect: z.number().nullable(),
          anaerobicTrainingEffect: z.number().nullable(),
          normPower: z.number().nullable(),
          avgStrideLength: z.number().nullable(),
          deviceId: z.number().nullable(),
          maxDoubleCadence: z.number().nullable(),
          isElevationCorrected: z.boolean().nullable(),
          isDecoDive: z.boolean().nullable(),
          summarizedDiveInfo: z
            .looseObject({
              summarizedDiveGases: z.array(z.unknown()).nullable(),
            })
            .nullable(),
          manufacturer: z.string().nullable(),
          lapCount: z.number().nullable(),
          isAtpActivity: z.boolean().nullable(),
          waterEstimated: z.number().nullable(),
          trainingEffectLabel: z.string().nullable(),
          activityTrainingLoad: z.number().nullable(),
          minActivityLapDuration: z.number().nullable(),
          aerobicTrainingEffectMessage: z.string().nullable(),
          anaerobicTrainingEffectMessage: z.string().nullable(),
          splitSummaries: z.array(z.looseObject({}).nullable()).nullable(),
          hasSplits: z.boolean().nullable(),
          hasIntensityIntervals: z.boolean().nullable(),
          isManualActivity: z.boolean().nullable(),
          hasHeatMap: z.boolean().nullable(),
          fastestSplit_1000: z.number().nullable(),
          fastestSplit_1609: z.number().nullable(),
          hrTimeInZone_1: z.number().nullable(),
          hrTimeInZone_2: z.number().nullable(),
          hrTimeInZone_3: z.number().nullable(),
          hrTimeInZone_4: z.number().nullable(),
          hrTimeInZone_5: z.number().nullable(),
          powerTimeInZone_1: z.number().nullable(),
          powerTimeInZone_2: z.number().nullable(),
          powerTimeInZone_3: z.number().nullable(),
          powerTimeInZone_4: z.number().nullable(),
          powerTimeInZone_5: z.number().nullable(),
          endTimeGMT: z.string().nullable(),
          qualifyingDive: z.boolean().nullable(),
          activityUUID: z.string().nullable(),
          pr: z.boolean().nullable(),
          favorite: z.boolean().nullable(),
          purposeful: z.boolean().nullable(),
          parent: z.boolean().nullable(),
          decoDive: z.boolean().nullable(),
          manualActivity: z.boolean().nullable(),
          autoCalcCalories: z.boolean().nullable(),
          elevationCorrected: z.boolean().nullable(),
          atpActivity: z.boolean().nullable(),
          elevationGain: z.number().nullable().optional(),
          elevationLoss: z.number().nullable().optional(),
          startLatitude: z.number().nullable().optional(),
          startLongitude: z.number().nullable().optional(),
          vO2MaxValue: z.number().nullable().optional(),
          minTemperature: z.number().nullable().optional(),
          maxTemperature: z.number().nullable().optional(),
          minElevation: z.number().nullable().optional(),
          maxElevation: z.number().nullable().optional(),
          avgElevation: z.number().nullable().optional(),
          maxVerticalSpeed: z.number().nullable().optional(),
          locationName: z.string().nullable().optional(),
          endLatitude: z.number().nullable().optional(),
          endLongitude: z.number().nullable().optional(),
          avgGradeAdjustedSpeed: z.number().nullable().optional(),
          fastestSplit_5000: z.number().nullable().optional(),
          fastestSplit_10000: z.number().nullable().optional(),
          workoutId: z.number().nullable().optional(),
          moderateIntensityMinutes: z.number().nullable().optional(),
          vigorousIntensityMinutes: z.number().nullable().optional(),
        })
        .nullable(),
    )
    .nullable(),
  activitiesByDate: z
    .array(
      z
        .looseObject({
          activityId: z.number().nullable(),
          activityName: z.string().nullable(),
          startTimeLocal: z.string().nullable(),
          startTimeGMT: z.string().nullable(),
          activityType: z
            .looseObject({
              typeId: z.number().nullable(),
              typeKey: z.string().nullable(),
              parentTypeId: z.number().nullable(),
              isHidden: z.boolean().nullable(),
              restricted: z.boolean().nullable(),
              trimmable: z.boolean().nullable(),
            })
            .nullable(),
          eventType: z
            .looseObject({
              typeId: z.number().nullable(),
              typeKey: z.string().nullable(),
              sortOrder: z.number().nullable(),
            })
            .nullable(),
          isFavorite: z.boolean().nullable(),
          isPR: z.boolean().nullable(),
          isAutoCalcCalories: z.boolean().nullable(),
          isParent: z.boolean().nullable(),
          distance: z.number().nullable(),
          duration: z.number().nullable(),
          elapsedDuration: z.number().nullable(),
          movingDuration: z.number().nullable(),
          elevationGain: z.number().nullable(),
          elevationLoss: z.number().nullable(),
          averageSpeed: z.number().nullable(),
          maxSpeed: z.number().nullable(),
          startLatitude: z.number().nullable(),
          startLongitude: z.number().nullable(),
          hasPolyline: z.boolean().nullable(),
          hasImages: z.boolean().nullable(),
          ownerId: z.number().nullable(),
          ownerDisplayName: z.string().nullable(),
          ownerFullName: z.string().nullable(),
          ownerProfileImageUrlSmall: z.string().nullable(),
          ownerProfileImageUrlMedium: z.string().nullable(),
          ownerProfileImageUrlLarge: z.string().nullable(),
          calories: z.number().nullable(),
          bmrCalories: z.number().nullable(),
          averageHR: z.number().nullable(),
          maxHR: z.number().nullable(),
          averageRunningCadenceInStepsPerMinute: z.number().nullable(),
          maxRunningCadenceInStepsPerMinute: z.number().nullable(),
          steps: z.number().nullable(),
          userRoles: z.array(z.string().nullable()).nullable(),
          privacy: z
            .looseObject({
              typeId: z.number().nullable(),
              typeKey: z.string().nullable(),
            })
            .nullable(),
          userPro: z.boolean().nullable(),
          hasVideo: z.boolean().nullable(),
          isPurposeful: z.boolean().nullable(),
          timeZoneId: z.number().nullable(),
          beginTimestamp: z.number().nullable(),
          sportTypeId: z.number().nullable(),
          avgPower: z.number().nullable(),
          maxPower: z.number().nullable(),
          aerobicTrainingEffect: z.number().nullable(),
          anaerobicTrainingEffect: z.number().nullable(),
          normPower: z.number().nullable(),
          avgStrideLength: z.number().nullable(),
          vO2MaxValue: z.number().nullable(),
          deviceId: z.number().nullable(),
          minTemperature: z.number().nullable(),
          maxTemperature: z.number().nullable(),
          minElevation: z.number().nullable(),
          maxElevation: z.number().nullable(),
          avgElevation: z.number().nullable(),
          maxDoubleCadence: z.number().nullable(),
          isElevationCorrected: z.boolean().nullable(),
          isDecoDive: z.boolean().nullable(),
          summarizedDiveInfo: z
            .looseObject({
              summarizedDiveGases: z.array(z.unknown()).nullable(),
            })
            .nullable(),
          maxVerticalSpeed: z.number().nullable(),
          manufacturer: z.string().nullable(),
          locationName: z.string().nullable(),
          lapCount: z.number().nullable(),
          endLatitude: z.number().nullable(),
          endLongitude: z.number().nullable(),
          isAtpActivity: z.boolean().nullable(),
          waterEstimated: z.number().nullable(),
          trainingEffectLabel: z.string().nullable(),
          activityTrainingLoad: z.number().nullable(),
          minActivityLapDuration: z.number().nullable(),
          aerobicTrainingEffectMessage: z.string().nullable(),
          anaerobicTrainingEffectMessage: z.string().nullable(),
          splitSummaries: z.array(z.looseObject({}).nullable()).nullable(),
          hasSplits: z.boolean().nullable(),
          hasIntensityIntervals: z.boolean().nullable(),
          isManualActivity: z.boolean().nullable(),
          avgGradeAdjustedSpeed: z.number().nullable(),
          hasHeatMap: z.boolean().nullable(),
          fastestSplit_1000: z.number().nullable(),
          fastestSplit_1609: z.number().nullable(),
          hrTimeInZone_1: z.number().nullable(),
          hrTimeInZone_2: z.number().nullable(),
          hrTimeInZone_3: z.number().nullable(),
          hrTimeInZone_4: z.number().nullable(),
          hrTimeInZone_5: z.number().nullable(),
          powerTimeInZone_1: z.number().nullable(),
          powerTimeInZone_2: z.number().nullable(),
          powerTimeInZone_3: z.number().nullable(),
          powerTimeInZone_4: z.number().nullable(),
          powerTimeInZone_5: z.number().nullable(),
          endTimeGMT: z.string().nullable(),
          qualifyingDive: z.boolean().nullable(),
          activityUUID: z.string().nullable(),
          pr: z.boolean().nullable(),
          favorite: z.boolean().nullable(),
          purposeful: z.boolean().nullable(),
          parent: z.boolean().nullable(),
          decoDive: z.boolean().nullable(),
          manualActivity: z.boolean().nullable(),
          autoCalcCalories: z.boolean().nullable(),
          elevationCorrected: z.boolean().nullable(),
          atpActivity: z.boolean().nullable(),
          fastestSplit_5000: z.number().nullable().optional(),
          fastestSplit_10000: z.number().nullable().optional(),
        })
        .nullable(),
    )
    .nullable(),
  activityChartDetails: z
    .looseObject({
      activityId: z.number().nullable(),
      measurementCount: z.number().nullable(),
      metricsCount: z.number().nullable(),
      totalMetricsCount: z.number().nullable(),
      metricDescriptors: z
        .array(
          z
            .looseObject({
              metricsIndex: z.number().nullable(),
              key: z.string().nullable(),
              unit: z.looseObject({}).nullable(),
            })
            .nullable(),
        )
        .nullable(),
      activityDetailMetrics: z
        .array(
          z
            .looseObject({
              metrics: z.array(z.unknown()).nullable(),
            })
            .nullable(),
        )
        .nullable(),
      geoPolylineDTO: z
        .looseObject({
          polyline: z.array(z.unknown()).nullable(),
          startPoint: z.unknown().optional(),
          endPoint: z.unknown().optional(),
          minLat: z.unknown().optional(),
          maxLat: z.unknown().optional(),
          minLon: z.unknown().optional(),
          maxLon: z.unknown().optional(),
        })
        .nullable(),
      detailsAvailable: z.boolean().nullable(),
      heartRateDTOs: z.unknown().optional(),
      pendingData: z.unknown().optional(),
    })
    .nullable(),
  activityDetails: z
    .looseObject({
      activityId: z.number().nullable(),
      activityUUID: z
        .looseObject({
          uuid: z.string().nullable(),
        })
        .nullable(),
      activityName: z.string().nullable(),
      userProfileId: z.number().nullable(),
      isMultiSportParent: z.boolean().nullable(),
      activityTypeDTO: z
        .looseObject({
          typeId: z.number().nullable(),
          typeKey: z.string().nullable(),
          parentTypeId: z.number().nullable(),
          isHidden: z.boolean().nullable(),
          restricted: z.boolean().nullable(),
          trimmable: z.boolean().nullable(),
        })
        .nullable(),
      eventTypeDTO: z
        .looseObject({
          typeId: z.number().nullable(),
          typeKey: z.string().nullable(),
          sortOrder: z.number().nullable(),
        })
        .nullable(),
      accessControlRuleDTO: z
        .looseObject({
          typeId: z.number().nullable(),
          typeKey: z.string().nullable(),
        })
        .nullable(),
      timeZoneUnitDTO: z
        .looseObject({
          unitId: z.number().nullable(),
          unitKey: z.string().nullable(),
          factor: z.number().nullable(),
          timeZone: z.string().nullable(),
        })
        .nullable(),
      metadataDTO: z
        .looseObject({
          isOriginal: z.boolean().nullable(),
          deviceApplicationInstallationId: z.number().nullable(),
          fileFormat: z
            .looseObject({
              formatId: z.number().nullable(),
              formatKey: z.string().nullable(),
            })
            .nullable(),
          lastUpdateDate: z.string().nullable(),
          uploadedDate: z.string().nullable(),
          hasPolyline: z.boolean().nullable(),
          hasChartData: z.boolean().nullable(),
          hasHrTimeInZones: z.boolean().nullable(),
          hasPowerTimeInZones: z.boolean().nullable(),
          userInfoDto: z
            .looseObject({
              userProfilePk: z.number().nullable(),
              displayname: z.string().nullable(),
              fullname: z.string().nullable(),
              profileImageUrlLarge: z.string().nullable(),
              profileImageUrlMedium: z.string().nullable(),
              profileImageUrlSmall: z.string().nullable(),
              userPro: z.boolean().nullable(),
            })
            .nullable(),
          childIds: z.array(z.unknown()).nullable(),
          childActivityTypes: z.array(z.unknown()).nullable(),
          activityImages: z.array(z.unknown()).nullable(),
          manufacturer: z.string().nullable(),
          lapCount: z.number().nullable(),
          deviceMetaDataDTO: z
            .looseObject({
              deviceId: z.string().nullable(),
              deviceTypePk: z.number().nullable(),
              deviceVersionPk: z.number().nullable(),
            })
            .nullable(),
          hasIntensityIntervals: z.boolean().nullable(),
          hasSplits: z.boolean().nullable(),
          hasRunPowerWindData: z.boolean().nullable(),
          hasHeatMap: z.boolean().nullable(),
          sessionResultType: z.string().nullable(),
          hasMultiDayActivities: z.boolean().nullable(),
          personalRecord: z.boolean().nullable(),
          gcj02: z.boolean().nullable(),
          runPowerWindDataEnabled: z.boolean().nullable(),
          manualActivity: z.boolean().nullable(),
          trimmed: z.boolean().nullable(),
          autoCalcCalories: z.boolean().nullable(),
          favorite: z.boolean().nullable(),
          elevationCorrected: z.boolean().nullable(),
          agentApplicationInstallationId: z.unknown().optional(),
          agentString: z.unknown().optional(),
          associatedCourseId: z.unknown().optional(),
          videoUrl: z.unknown().optional(),
          sensors: z.unknown().optional(),
          diveNumber: z.unknown().optional(),
          associatedWorkoutId: z.unknown().optional(),
          isAtpActivity: z.unknown().optional(),
          eBikeMaxAssistModes: z.unknown().optional(),
          eBikeBatteryUsage: z.unknown().optional(),
          eBikeBatteryRemaining: z.unknown().optional(),
          eBikeAssistModeInfoDTOList: z.unknown().optional(),
          calendarEventInfo: z.unknown().optional(),
          groupRideUUID: z.unknown().optional(),
        })
        .nullable(),
      summaryDTO: z
        .looseObject({
          startTimeLocal: z.string().nullable(),
          startTimeGMT: z.string().nullable(),
          startLatitude: z.number().nullable(),
          startLongitude: z.number().nullable(),
          distance: z.number().nullable(),
          duration: z.number().nullable(),
          movingDuration: z.number().nullable(),
          elapsedDuration: z.number().nullable(),
          elevationGain: z.number().nullable(),
          elevationLoss: z.number().nullable(),
          maxElevation: z.number().nullable(),
          minElevation: z.number().nullable(),
          avgElevation: z.number().nullable(),
          averageSpeed: z.number().nullable(),
          averageMovingSpeed: z.number().nullable(),
          maxSpeed: z.number().nullable(),
          calories: z.number().nullable(),
          bmrCalories: z.number().nullable(),
          averageHR: z.number().nullable(),
          maxHR: z.number().nullable(),
          minHR: z.number().nullable(),
          averageRunCadence: z.number().nullable(),
          maxRunCadence: z.number().nullable(),
          averageTemperature: z.number().nullable(),
          maxTemperature: z.number().nullable(),
          minTemperature: z.number().nullable(),
          averagePower: z.number().nullable(),
          maxPower: z.number().nullable(),
          minPower: z.number().nullable(),
          normalizedPower: z.number().nullable(),
          totalWork: z.number().nullable(),
          strideLength: z.number().nullable(),
          trainingEffect: z.number().nullable(),
          anaerobicTrainingEffect: z.number().nullable(),
          aerobicTrainingEffectMessage: z.string().nullable(),
          anaerobicTrainingEffectMessage: z.string().nullable(),
          endLatitude: z.number().nullable(),
          endLongitude: z.number().nullable(),
          maxVerticalSpeed: z.number().nullable(),
          waterEstimated: z.number().nullable(),
          trainingEffectLabel: z.string().nullable(),
          activityTrainingLoad: z.number().nullable(),
          minActivityLapDuration: z.number().nullable(),
          steps: z.number().nullable(),
          avgGradeAdjustedSpeed: z.number().nullable(),
        })
        .nullable(),
      locationName: z.string().nullable(),
      splitSummaries: z
        .array(
          z
            .looseObject({
              distance: z.number().nullable(),
              duration: z.number().nullable(),
              movingDuration: z.number().nullable(),
              elevationGain: z.number().nullable(),
              elevationLoss: z.number().nullable(),
              averageSpeed: z.number().nullable(),
              averageMovingSpeed: z.number().nullable(),
              maxSpeed: z.number().nullable(),
              calories: z.number().nullable(),
              bmrCalories: z.number().nullable(),
              averageHR: z.number().nullable(),
              maxHR: z.number().nullable(),
              averageRunCadence: z.number().nullable(),
              maxRunCadence: z.number().nullable(),
              averageTemperature: z.number().nullable(),
              maxTemperature: z.number().nullable(),
              minTemperature: z.number().nullable(),
              averagePower: z.number().nullable(),
              maxPower: z.number().nullable(),
              normalizedPower: z.number().nullable(),
              strideLength: z.number().nullable(),
              totalExerciseReps: z.number().nullable(),
              avgVerticalSpeed: z.number().nullable(),
              avgGradeAdjustedSpeed: z.number().nullable(),
              splitType: z.string().nullable(),
              noOfSplits: z.number().nullable(),
              maxElevationGain: z.number().nullable(),
              averageElevationGain: z.number().nullable(),
              maxDistance: z.number().nullable(),
              maxDistanceWithPrecision: z.number().nullable(),
              avgStepFrequency: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
    })
    .nullable(),
  activityExerciseSets: z
    .looseObject({
      activityId: z.number().nullable(),
      exerciseSets: z.unknown().optional(),
    })
    .nullable(),
  activityGear: z
    .array(
      z
        .looseObject({
          gearPk: z.number().nullable(),
          uuid: z.string().nullable(),
          userProfilePk: z.number().nullable(),
          gearMakeName: z.string().nullable(),
          gearModelName: z.string().nullable(),
          gearTypeName: z.string().nullable(),
          gearStatusName: z.string().nullable(),
          displayName: z.string().nullable(),
          customMakeModel: z.string().nullable(),
          dateBegin: z.string().nullable(),
          maximumMeters: z.number().nullable(),
          notified: z.boolean().nullable(),
          createDate: z.string().nullable(),
          updateDate: z.string().nullable(),
          imageNameLarge: z.unknown().optional(),
          imageNameMedium: z.unknown().optional(),
          imageNameSmall: z.unknown().optional(),
          dateEnd: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
  activityHrZones: z
    .array(
      z
        .looseObject({
          zoneNumber: z.number().nullable(),
          secsInZone: z.number().nullable(),
          zoneLowBoundary: z.number().nullable(),
        })
        .nullable(),
    )
    .nullable(),
  activitySplits: z
    .looseObject({
      activityId: z.number().nullable(),
      lapDTOs: z
        .array(
          z
            .looseObject({
              startTimeGMT: z.string().nullable(),
              startLatitude: z.number().nullable(),
              startLongitude: z.number().nullable(),
              distance: z.number().nullable(),
              duration: z.number().nullable(),
              movingDuration: z.number().nullable(),
              elapsedDuration: z.number().nullable(),
              elevationGain: z.number().nullable(),
              elevationLoss: z.number().nullable(),
              maxElevation: z.number().nullable(),
              minElevation: z.number().nullable(),
              averageSpeed: z.number().nullable(),
              averageMovingSpeed: z.number().nullable(),
              maxSpeed: z.number().nullable(),
              calories: z.number().nullable(),
              bmrCalories: z.number().nullable(),
              averageHR: z.number().nullable(),
              maxHR: z.number().nullable(),
              averageRunCadence: z.number().nullable(),
              maxRunCadence: z.number().nullable(),
              averageTemperature: z.number().nullable(),
              maxTemperature: z.number().nullable(),
              minTemperature: z.number().nullable(),
              averagePower: z.number().nullable(),
              maxPower: z.number().nullable(),
              minPower: z.number().nullable(),
              normalizedPower: z.number().nullable(),
              totalWork: z.number().nullable(),
              strideLength: z.number().nullable(),
              endLatitude: z.number().nullable(),
              endLongitude: z.number().nullable(),
              maxVerticalSpeed: z.number().nullable(),
              avgGradeAdjustedSpeed: z.number().nullable(),
              lapIndex: z.number().nullable(),
              lengthDTOs: z.array(z.unknown()).nullable(),
              connectIQMeasurement: z.array(z.unknown()).nullable(),
              messageIndex: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      eventDTOs: z
        .array(
          z
            .looseObject({
              startTimeGMT: z.string().nullable(),
              startTimeGMTDoubleValue: z.number().nullable(),
              sectionTypeDTO: z.looseObject({}).nullable(),
            })
            .nullable(),
        )
        .nullable(),
    })
    .nullable(),
  activityTypedSplits: z
    .looseObject({
      activityId: z.number().nullable(),
      activityUUID: z
        .looseObject({
          uuid: z.string().nullable(),
        })
        .nullable(),
      splits: z
        .array(
          z
            .looseObject({
              startTimeLocal: z.string().nullable(),
              startTimeGMT: z.string().nullable(),
              startLatitude: z.number().nullable(),
              startLongitude: z.number().nullable(),
              distance: z.number().nullable(),
              duration: z.number().nullable(),
              movingDuration: z.number().nullable(),
              elapsedDuration: z.number().nullable(),
              elevationGain: z.number().nullable(),
              elevationLoss: z.number().nullable(),
              averageSpeed: z.number().nullable(),
              averageMovingSpeed: z.number().nullable(),
              maxSpeed: z.number().nullable(),
              calories: z.number().nullable(),
              bmrCalories: z.number().nullable(),
              averageHR: z.number().nullable(),
              maxHR: z.number().nullable(),
              averageRunCadence: z.number().nullable(),
              maxRunCadence: z.number().nullable(),
              averageTemperature: z.number().nullable(),
              maxTemperature: z.number().nullable(),
              minTemperature: z.number().nullable(),
              averagePower: z.number().nullable(),
              maxPower: z.number().nullable(),
              normalizedPower: z.number().nullable(),
              strideLength: z.number().nullable(),
              totalExerciseReps: z.number().nullable(),
              endLatitude: z.number().nullable(),
              endLongitude: z.number().nullable(),
              avgVerticalSpeed: z.number().nullable(),
              avgGradeAdjustedSpeed: z.number().nullable(),
              avgElapsedDurationVerticalSpeed: z.number().nullable(),
              type: z.string().nullable(),
              messageIndex: z.number().nullable(),
              endTimeGMT: z.string().nullable(),
              startElevation: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
    })
    .nullable(),
  activityTypes: z
    .array(
      z
        .looseObject({
          typeId: z.number().nullable(),
          typeKey: z.string().nullable(),
          isHidden: z.boolean().nullable(),
          restricted: z.boolean().nullable(),
          trimmable: z.boolean().nullable(),
          parentTypeId: z.number().nullable().optional(),
        })
        .nullable(),
    )
    .nullable(),
  activityWeather: z
    .looseObject({
      issueDate: z.string().nullable(),
      temp: z.number().nullable(),
      apparentTemp: z.number().nullable(),
      dewPoint: z.number().nullable(),
      relativeHumidity: z.number().nullable(),
      windDirection: z.number().nullable(),
      windDirectionCompassPoint: z.string().nullable(),
      windSpeed: z.number().nullable(),
      latitude: z.number().nullable(),
      longitude: z.number().nullable(),
      weatherStationDTO: z
        .looseObject({
          id: z.string().nullable(),
          name: z.string().nullable(),
          timezone: z.unknown().optional(),
        })
        .nullable(),
      weatherTypeDTO: z
        .looseObject({
          desc: z.string().nullable(),
          weatherTypePk: z.unknown().optional(),
          image: z.unknown().optional(),
        })
        .nullable(),
      windGust: z.unknown().optional(),
    })
    .nullable(),
  bodyBattery: z
    .array(
      z
        .looseObject({
          date: z.string().nullable(),
          charged: z.number().nullable(),
          drained: z.number().nullable(),
          startTimestampGMT: z.string().nullable(),
          endTimestampGMT: z.string().nullable(),
          startTimestampLocal: z.string().nullable(),
          endTimestampLocal: z.string().nullable(),
          bodyBatteryValuesArray: z.array(z.array(z.unknown()).nullable()).nullable(),
          bodyBatteryValueDescriptorDTOList: z.array(z.looseObject({}).nullable()).nullable(),
        })
        .nullable(),
    )
    .nullable(),
  bodyBatteryEvents: z.array(z.unknown()).nullable(),
  bodyComposition: z
    .looseObject({
      startDate: z.string().nullable(),
      endDate: z.string().nullable(),
      dateWeightList: z.array(z.unknown()).nullable(),
      totalAverage: z
        .looseObject({
          from: z.number().nullable(),
          until: z.number().nullable(),
          weight: z.unknown().optional(),
          bmi: z.unknown().optional(),
          bodyFat: z.unknown().optional(),
          bodyWater: z.unknown().optional(),
          boneMass: z.unknown().optional(),
          muscleMass: z.unknown().optional(),
          physiqueRating: z.unknown().optional(),
          visceralFat: z.unknown().optional(),
          metabolicAge: z.unknown().optional(),
        })
        .nullable(),
    })
    .nullable(),
  calendar: z
    .looseObject({
      startDayOfMonth: z.number().nullable(),
      numOfDaysInMonth: z.number().nullable(),
      numOfDaysInPrevMonth: z.number().nullable(),
      month: z.number().nullable(),
      year: z.number().nullable(),
      calendarItems: z
        .array(
          z
            .looseObject({
              id: z.number().nullable(),
              itemType: z.string().nullable(),
              activityTypeId: z.number().nullable(),
              title: z.string().nullable(),
              date: z.string().nullable(),
              duration: z.number().nullable(),
              distance: z.number().nullable(),
              calories: z.number().nullable(),
              isParent: z.boolean().nullable(),
              startTimestampLocal: z.string().nullable(),
              elapsedDuration: z.number().nullable(),
              lapCount: z.number().nullable(),
              protectedWorkoutSchedule: z.boolean().nullable(),
              maxSpeed: z.number().nullable(),
              averageHR: z.number().nullable(),
              hasSplits: z.boolean().nullable(),
              autoCalcCalories: z.boolean().nullable(),
              decoDive: z.boolean().nullable(),
              shareableEvent: z.boolean().nullable(),
              groupId: z.unknown().optional(),
              trainingPlanId: z.unknown().optional(),
              wellnessActivityUuid: z.unknown().optional(),
              floorsClimbed: z.unknown().optional(),
              avgRespirationRate: z.unknown().optional(),
              unitOfPoolLength: z.unknown().optional(),
              weight: z.unknown().optional(),
              difference: z.unknown().optional(),
              courseId: z.unknown().optional(),
              courseName: z.unknown().optional(),
              sportTypeKey: z.unknown().optional(),
              url: z.unknown().optional(),
              isStart: z.unknown().optional(),
              isRace: z.unknown().optional(),
              recurrenceId: z.unknown().optional(),
              parentId: z.unknown().optional(),
              userBadgeId: z.unknown().optional(),
              badgeCategoryTypeId: z.unknown().optional(),
              badgeCategoryTypeDesc: z.unknown().optional(),
              badgeAwardedDate: z.unknown().optional(),
              badgeViewed: z.unknown().optional(),
              hideBadge: z.unknown().optional(),
              eventTimeLocal: z.unknown().optional(),
              diveNumber: z.unknown().optional(),
              maxDepth: z.unknown().optional(),
              avgDepth: z.unknown().optional(),
              surfaceInterval: z.unknown().optional(),
              bottomTime: z.unknown().optional(),
              atpPlanId: z.unknown().optional(),
              workoutId: z.unknown().optional(),
              activeSets: z.unknown().optional(),
              strokes: z.unknown().optional(),
              noOfSplits: z.number().nullable().optional(),
              maxGradeValue: z.unknown().optional(),
              totalAscent: z.number().nullable().optional(),
              differenceStress: z.unknown().optional(),
              climbDuration: z.number().nullable().optional(),
              activeSplitSummaryDuration: z.number().nullable().optional(),
              activeSplitSummaryDistance: z.number().nullable().optional(),
              maxSplitDistance: z.number().nullable().optional(),
              maxDistanceWithPrecision: z.number().nullable().optional(),
              maxSplitSpeed: z.number().nullable().optional(),
              location: z.unknown().optional(),
              shareableEventUuid: z.unknown().optional(),
              splitSummaryMode: z.unknown().optional(),
              completionTarget: z.unknown().optional(),
              workoutUuid: z.unknown().optional(),
              napStartTimeLocal: z.unknown().optional(),
              beginPackWeight: z.unknown().optional(),
              maxPackWeight: z.unknown().optional(),
              phasedTrainingPlan: z.unknown().optional(),
              primaryEvent: z.unknown().optional(),
              subscribed: z.unknown().optional(),
            })
            .nullable(),
        )
        .nullable(),
    })
    .nullable(),
  cyclingFtp: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      version: z.number().nullable(),
      calendarDate: z.string().nullable(),
      isStale: z.boolean().nullable(),
      sequence: z.number().nullable(),
      sport: z.string().nullable(),
      functionalThresholdPower: z.number().nullable(),
      biometricSourceType: z.string().nullable(),
    })
    .nullable(),
  dailyStressStats: z
    .array(
      z
        .looseObject({
          calendarDate: z.string().nullable(),
          values: z
            .looseObject({
              highStressDuration: z.number().nullable(),
              lowStressDuration: z.number().nullable(),
              overallStressLevel: z.number().nullable(),
              restStressDuration: z.number().nullable(),
              mediumStressDuration: z.number().nullable(),
            })
            .nullable(),
        })
        .nullable(),
    )
    .nullable(),
  deviceLastUsed: z
    .looseObject({
      userDeviceId: z.number().nullable(),
      userProfileNumber: z.number().nullable(),
      applicationNumber: z.number().nullable(),
      lastUsedDeviceApplicationKey: z.string().nullable(),
      lastUsedDeviceName: z.string().nullable(),
      lastUsedDeviceUploadTime: z.number().nullable(),
      imageUrl: z.string().nullable(),
      released: z.boolean().nullable(),
    })
    .nullable(),
  devices: z
    .array(
      z
        .looseObject({
          appSupport: z.boolean().nullable(),
          applicationKey: z.string().nullable(),
          deviceTypePk: z.number().nullable(),
          bluetoothClassicDevice: z.boolean().nullable(),
          bluetoothLowEnergyDevice: z.boolean().nullable(),
          deviceCategories: z.array(z.string().nullable()).nullable(),
          deviceSettingsFile: z.string().nullable(),
          displayOrder: z.number().nullable(),
          golfDisplayOrder: z.number().nullable(),
          hasOpticalHeartRate: z.boolean().nullable(),
          highlighted: z.boolean().nullable(),
          hybrid: z.boolean().nullable(),
          imageUrl: z.string().nullable(),
          minGCMAndroidVersion: z.number().nullable(),
          minGCMWindowsVersion: z.number().nullable(),
          minGCMiOSVersion: z.number().nullable(),
          minGCMHarmonyVersion: z.number().nullable(),
          minGolfAppiOSVersion: z.number().nullable(),
          minGolfAppAndroidVersion: z.number().nullable(),
          partNumber: z.string().nullable(),
        })
        .nullable(),
    )
    .nullable(),
  enduranceScore: z.unknown(), // 204 No Content when there is no data
  enduranceScoreRange: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      startDate: z.string().nullable(),
      endDate: z.string().nullable(),
      groupMap: z
        .record(
          z.string(),
          z
            .looseObject({
              enduranceContributorDTOList: z.array(z.unknown()).nullable(),
              groupAverage: z.unknown().optional(),
              groupMax: z.unknown().optional(),
            })
            .nullable(),
        )
        .nullable(),
      avg: z.unknown().optional(),
      max: z.unknown().optional(),
      enduranceScoreDTO: z.unknown().optional(),
    })
    .nullable(),
  fitnessAge: z
    .looseObject({
      chronologicalAge: z.number().nullable(),
      fitnessAge: z.number().nullable(),
      achievableFitnessAge: z.number().nullable(),
      previousFitnessAge: z.number().nullable(),
      components: z
        .looseObject({
          vigorousDaysAvg: z
            .looseObject({
              value: z.number().nullable(),
              targetValue: z.number().nullable(),
              potentialAge: z.number().nullable(),
              priority: z.number().nullable(),
              stale: z.boolean().nullable(),
              numOfWeeksForIm: z.number().nullable(),
            })
            .nullable(),
          rhr: z
            .looseObject({
              value: z.number().nullable(),
              stale: z.boolean().nullable(),
            })
            .nullable(),
          vigorousMinutesAvg: z
            .looseObject({
              value: z.number().nullable(),
              targetValue: z.number().nullable(),
              potentialAge: z.number().nullable(),
              priority: z.number().nullable(),
              stale: z.boolean().nullable(),
              numOfWeeksForIm: z.number().nullable(),
            })
            .nullable(),
          bmi: z
            .looseObject({
              value: z.number().nullable(),
              targetValue: z.number().nullable(),
              improvementValue: z.number().nullable(),
              potentialAge: z.number().nullable(),
              priority: z.number().nullable(),
              stale: z.boolean().nullable(),
              lastMeasurementDate: z.string().nullable(),
            })
            .nullable(),
        })
        .nullable(),
      lastUpdated: z.string().nullable(),
    })
    .nullable(),
  floors: z
    .looseObject({
      startTimestampGMT: z.string().nullable(),
      endTimestampGMT: z.string().nullable(),
      startTimestampLocal: z.string().nullable(),
      endTimestampLocal: z.string().nullable(),
      floorsValueDescriptorDTOList: z
        .array(
          z
            .looseObject({
              index: z.number().nullable(),
              key: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      floorValuesArray: z.array(z.array(z.unknown()).nullable()).nullable(),
    })
    .nullable(),
  gear: z
    .array(
      z
        .looseObject({
          gearPk: z.number().nullable(),
          uuid: z.string().nullable(),
          userProfilePk: z.number().nullable(),
          gearMakeName: z.string().nullable(),
          gearModelName: z.string().nullable(),
          gearTypeName: z.string().nullable(),
          gearStatusName: z.string().nullable(),
          customMakeModel: z.string().nullable(),
          dateBegin: z.string().nullable(),
          maximumMeters: z.number().nullable(),
          notified: z.boolean().nullable(),
          createDate: z.string().nullable(),
          updateDate: z.string().nullable(),
          displayName: z.string().nullable().optional(),
          imageNameLarge: z.unknown().optional(),
          imageNameMedium: z.unknown().optional(),
          imageNameSmall: z.unknown().optional(),
          dateEnd: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
  goals: z.array(z.unknown()).nullable(),
  heartRateZones: z
    .array(
      z
        .looseObject({
          trainingMethod: z.string().nullable(),
          restingHeartRateUsed: z.number().nullable(),
          zone1Floor: z.number().nullable(),
          zone2Floor: z.number().nullable(),
          zone3Floor: z.number().nullable(),
          zone4Floor: z.number().nullable(),
          zone5Floor: z.number().nullable(),
          maxHeartRateUsed: z.number().nullable(),
          restingHrAutoUpdateUsed: z.boolean().nullable(),
          sport: z.string().nullable(),
          changeState: z.string().nullable(),
          lactateThresholdHeartRateUsed: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
  heartRates: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      calendarDate: z.string().nullable(),
      startTimestampGMT: z.string().nullable(),
      endTimestampGMT: z.string().nullable(),
      startTimestampLocal: z.string().nullable(),
      endTimestampLocal: z.string().nullable(),
      maxHeartRate: z.number().nullable(),
      minHeartRate: z.number().nullable(),
      restingHeartRate: z.number().nullable(),
      lastSevenDaysAvgRestingHeartRate: z.number().nullable(),
      heartRateValueDescriptors: z
        .array(
          z
            .looseObject({
              index: z.number().nullable(),
              key: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      heartRateValues: z.array(z.array(z.number().nullable()).nullable()).nullable(),
    })
    .nullable(),
  hillScore: z.unknown(), // 204 No Content when there is no data
  hillScoreRange: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      startDate: z.string().nullable(),
      endDate: z.string().nullable(),
      periodAvgScore: z.record(z.string(), z.unknown()).nullable(),
      hillScoreDTOList: z.array(z.unknown()).nullable(),
      maxScore: z.unknown().optional(),
    })
    .nullable(),
  hrv: z
    .looseObject({
      hrvSummaries: z
        .array(
          z
            .looseObject({
              calendarDate: z.string().nullable(),
              weeklyAvg: z.number().nullable(),
              lastNightAvg: z.number().nullable(),
              lastNight5MinHigh: z.number().nullable(),
              baseline: z.looseObject({}).nullable(),
              status: z.string().nullable(),
              feedbackPhrase: z.string().nullable(),
              createTimeStamp: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      userProfilePk: z.number().nullable(),
    })
    .nullable(),
  hydration: z
    .looseObject({
      userId: z.number().nullable(),
      calendarDate: z.string().nullable(),
      goalInML: z.number().nullable(),
      valueInML: z.unknown().optional(),
      dailyAverageinML: z.unknown().optional(),
      lastEntryTimestampLocal: z.unknown().optional(),
      sweatLossInML: z.unknown().optional(),
      activityIntakeInML: z.unknown().optional(),
    })
    .nullable(),
  intensityMinutes: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      calendarDate: z.string().nullable(),
      startTimestampGMT: z.string().nullable(),
      endTimestampGMT: z.string().nullable(),
      startTimestampLocal: z.string().nullable(),
      endTimestampLocal: z.string().nullable(),
      weeklyModerate: z.number().nullable(),
      weeklyVigorous: z.number().nullable(),
      weeklyTotal: z.number().nullable(),
      weekGoal: z.number().nullable(),
      startDayMinutes: z.number().nullable(),
      endDayMinutes: z.number().nullable(),
      moderateMinutes: z.number().nullable(),
      vigorousMinutes: z.number().nullable(),
      dayOfGoalMet: z.unknown().optional(),
      imValueDescriptorsDTOList: z.unknown().optional(),
      imValuesArray: z.unknown().optional(),
    })
    .nullable(),
  lactateThreshold: z
    .array(
      z
        .looseObject({
          userProfilePK: z.number().nullable(),
          version: z.number().nullable(),
          calendarDate: z.string().nullable(),
          sequence: z.number().nullable(),
          hearRate: z.number().nullable(),
          speed: z.unknown().optional(),
          heartRateCycling: z.unknown().optional(),
          rowSpeed: z.unknown().optional(),
          heartRateRowing: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
  personalRecords: z
    .array(
      z
        .looseObject({
          id: z.number().nullable(),
          typeId: z.number().nullable(),
          status: z.string().nullable(),
          activityId: z.number().nullable(),
          value: z.number().nullable(),
          prStartTimeGmt: z.number().nullable(),
          prStartTimeGmtFormatted: z.string().nullable(),
          activityName: z.string().nullable().optional(),
          activityType: z.string().nullable().optional(),
          activityStartDateTimeInGMT: z.number().nullable().optional(),
          actStartDateTimeInGMTFormatted: z.string().nullable().optional(),
          activityStartDateTimeLocal: z.number().nullable().optional(),
          activityStartDateTimeLocalFormatted: z.string().nullable().optional(),
          prStartTimeLocal: z.number().nullable().optional(),
          prStartTimeLocalFormatted: z.string().nullable().optional(),
          prTypeLabelKey: z.unknown().optional(),
          poolLengthUnit: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
  primaryTrainingDevice: z
    .looseObject({
      PrimaryTrainingDevice: z
        .looseObject({
          deviceId: z.number().nullable(),
        })
        .nullable(),
      WearableDevices: z
        .looseObject({
          deviceWeights: z.array(z.looseObject({}).nullable()).nullable(),
          wearableDeviceCount: z.number().nullable(),
        })
        .nullable(),
      TrainingStatusOnlyDevices: z
        .looseObject({
          deviceWeights: z.array(z.unknown()).nullable(),
        })
        .nullable(),
      PrimaryTrainingDevices: z
        .looseObject({
          deviceWeights: z.array(z.looseObject({}).nullable()).nullable(),
          primaryTrainingDeviceCount: z.number().nullable(),
        })
        .nullable(),
      RegisteredDevices: z
        .array(
          z
            .looseObject({
              appSupport: z.boolean().nullable(),
              applicationKey: z.string().nullable(),
              deviceTypePk: z.number().nullable(),
              bluetoothClassicDevice: z.boolean().nullable(),
              bluetoothLowEnergyDevice: z.boolean().nullable(),
              deviceCategories: z.array(z.unknown()).nullable(),
              deviceSettingsFile: z.string().nullable(),
              displayOrder: z.number().nullable(),
              golfDisplayOrder: z.number().nullable(),
              hasOpticalHeartRate: z.boolean().nullable(),
              highlighted: z.boolean().nullable(),
              hybrid: z.boolean().nullable(),
              imageUrl: z.string().nullable(),
              minGCMAndroidVersion: z.number().nullable(),
              minGCMWindowsVersion: z.number().nullable(),
              minGCMiOSVersion: z.number().nullable(),
              minGCMHarmonyVersion: z.number().nullable(),
              minGolfAppiOSVersion: z.number().nullable(),
              minGolfAppAndroidVersion: z.number().nullable(),
              partNumber: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
    })
    .nullable(),
  progressSummary: z
    .array(
      z
        .looseObject({
          date: z.string().nullable(),
          countOfActivities: z.number().nullable(),
          stats: z
            .looseObject({
              running: z.looseObject({}).nullable(),
            })
            .nullable(),
        })
        .nullable(),
    )
    .nullable(),
  racePredictions: z
    .looseObject({
      userId: z.number().nullable(),
      calendarDate: z.string().nullable(),
      time5K: z.number().nullable(),
      time10K: z.number().nullable(),
      timeHalfMarathon: z.number().nullable(),
      timeMarathon: z.number().nullable(),
      fromCalendarDate: z.unknown().optional(),
      toCalendarDate: z.unknown().optional(),
    })
    .nullable(),
  respiration: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      calendarDate: z.string().nullable(),
      startTimestampGMT: z.string().nullable(),
      endTimestampGMT: z.string().nullable(),
      startTimestampLocal: z.string().nullable(),
      endTimestampLocal: z.string().nullable(),
      sleepStartTimestampGMT: z.string().nullable(),
      sleepEndTimestampGMT: z.string().nullable(),
      sleepStartTimestampLocal: z.string().nullable(),
      sleepEndTimestampLocal: z.string().nullable(),
      tomorrowSleepStartTimestampGMT: z.string().nullable(),
      tomorrowSleepEndTimestampGMT: z.string().nullable(),
      tomorrowSleepStartTimestampLocal: z.string().nullable(),
      tomorrowSleepEndTimestampLocal: z.string().nullable(),
      lowestRespirationValue: z.number().nullable(),
      highestRespirationValue: z.number().nullable(),
      avgWakingRespirationValue: z.number().nullable(),
      avgSleepRespirationValue: z.number().nullable(),
      avgTomorrowSleepRespirationValue: z.number().nullable(),
      respirationValueDescriptorsDTOList: z
        .array(
          z
            .looseObject({
              index: z.number().nullable(),
              key: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      respirationValuesArray: z.array(z.array(z.number().nullable()).nullable()).nullable(),
      respirationAveragesValueDescriptorDTOList: z
        .array(
          z
            .looseObject({
              respirationAveragesValueDescriptorIndex: z.number().nullable(),
              respirationAveragesValueDescriptionKey: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      respirationAveragesValuesArray: z.array(z.array(z.number().nullable()).nullable()).nullable(),
      respirationVersion: z.number().nullable(),
    })
    .nullable(),
  restingHeartRate: z
    .looseObject({
      userProfileId: z.number().nullable(),
      statisticsStartDate: z.string().nullable(),
      statisticsEndDate: z.string().nullable(),
      allMetrics: z
        .looseObject({
          metricsMap: z
            .looseObject({
              WELLNESS_RESTING_HEART_RATE: z.array(z.unknown()).nullable(),
            })
            .nullable(),
        })
        .nullable(),
      groupedMetrics: z.unknown().optional(),
    })
    .nullable(),
  runningTolerance: z.array(z.unknown()).nullable(),
  sleep: z
    .looseObject({
      dailySleepDTO: z
        .looseObject({
          id: z.number().nullable(),
          userProfilePK: z.number().nullable(),
          calendarDate: z.string().nullable(),
          sleepTimeSeconds: z.number().nullable(),
          napTimeSeconds: z.number().nullable(),
          sleepWindowConfirmed: z.boolean().nullable(),
          sleepWindowConfirmationType: z.string().nullable(),
          sleepStartTimestampGMT: z.number().nullable(),
          sleepEndTimestampGMT: z.number().nullable(),
          sleepStartTimestampLocal: z.number().nullable(),
          sleepEndTimestampLocal: z.number().nullable(),
          unmeasurableSleepSeconds: z.number().nullable(),
          deepSleepSeconds: z.number().nullable(),
          lightSleepSeconds: z.number().nullable(),
          remSleepSeconds: z.number().nullable(),
          awakeSleepSeconds: z.number().nullable(),
          deviceRemCapable: z.boolean().nullable(),
          retro: z.boolean().nullable(),
          sleepFromDevice: z.boolean().nullable(),
          averageRespirationValue: z.number().nullable(),
          lowestRespirationValue: z.number().nullable(),
          highestRespirationValue: z.number().nullable(),
          awakeCount: z.number().nullable(),
          avgSleepStress: z.number().nullable(),
          ageGroup: z.string().nullable(),
          sleepScoreFeedback: z.string().nullable(),
          sleepScoreInsight: z.string().nullable(),
          sleepScorePersonalizedInsight: z.string().nullable(),
          sleepScores: z
            .looseObject({
              totalDuration: z.looseObject({}).nullable(),
              stress: z.looseObject({}).nullable(),
              awakeCount: z.looseObject({}).nullable(),
              overall: z.looseObject({}).nullable(),
              remPercentage: z.looseObject({}).nullable(),
              restlessness: z.looseObject({}).nullable(),
              lightPercentage: z.looseObject({}).nullable(),
              deepPercentage: z.looseObject({}).nullable(),
            })
            .nullable(),
          sleepVersion: z.number().nullable(),
          autoSleepStartTimestampGMT: z.unknown().optional(),
          autoSleepEndTimestampGMT: z.unknown().optional(),
          sleepQualityTypePK: z.unknown().optional(),
          sleepResultTypePK: z.unknown().optional(),
        })
        .nullable(),
      sleepMovement: z
        .array(
          z
            .looseObject({
              startGMT: z.string().nullable(),
              endGMT: z.string().nullable(),
              activityLevel: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      remSleepData: z.boolean().nullable(),
      sleepLevels: z
        .array(
          z
            .looseObject({
              startGMT: z.string().nullable(),
              endGMT: z.string().nullable(),
              activityLevel: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      sleepRestlessMoments: z
        .array(
          z
            .looseObject({
              value: z.number().nullable(),
              startGMT: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      restlessMomentsCount: z.number().nullable(),
      wellnessEpochRespirationDataDTOList: z
        .array(
          z
            .looseObject({
              startTimeGMT: z.number().nullable(),
              respirationValue: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      wellnessEpochRespirationAveragesList: z
        .array(
          z
            .looseObject({
              epochEndTimestampGmt: z.number().nullable(),
              respirationAverageValue: z.number().nullable(),
              respirationHighValue: z.number().nullable().optional(),
              respirationLowValue: z.number().nullable().optional(),
            })
            .nullable(),
        )
        .nullable(),
      respirationVersion: z.number().nullable(),
      sleepHeartRate: z
        .array(
          z
            .looseObject({
              value: z.number().nullable(),
              startGMT: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      sleepStress: z
        .array(
          z
            .looseObject({
              value: z.number().nullable(),
              startGMT: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      sleepBodyBattery: z
        .array(
          z
            .looseObject({
              value: z.number().nullable(),
              startGMT: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      skinTempDataExists: z.boolean().nullable(),
      bodyBatteryChange: z.number().nullable(),
      restingHeartRate: z.number().nullable(),
    })
    .nullable(),
  sleepStats: z
    .looseObject({
      overallStats: z
        .looseObject({
          averageLocalSleepStartTime: z.number().nullable(),
          averageRespiration: z.number().nullable(),
          averageBodyBatteryChange: z.number().nullable(),
          averageSleepScore: z.number().nullable(),
          averageLocalSleepEndTime: z.number().nullable(),
          averageSleepSeconds: z.number().nullable(),
          averageRestingHeartRate: z.number().nullable(),
          averageSpO2: z.unknown().optional(),
          meanAvgHeartRate: z.unknown().optional(),
          averageSkinTempF: z.unknown().optional(),
          averageSkinTempC: z.unknown().optional(),
          averageSleepNeed: z.unknown().optional(),
        })
        .nullable(),
      individualStats: z
        .array(
          z
            .looseObject({
              calendarDate: z.string().nullable(),
              values: z.looseObject({}).nullable(),
            })
            .nullable(),
        )
        .nullable(),
    })
    .nullable(),
  spo2: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      calendarDate: z.string().nullable(),
      startTimestampGMT: z.string().nullable(),
      endTimestampGMT: z.string().nullable(),
      startTimestampLocal: z.string().nullable(),
      endTimestampLocal: z.string().nullable(),
      sleepStartTimestampGMT: z.string().nullable(),
      sleepEndTimestampGMT: z.string().nullable(),
      sleepStartTimestampLocal: z.string().nullable(),
      sleepEndTimestampLocal: z.string().nullable(),
      tomorrowSleepStartTimestampGMT: z.string().nullable(),
      tomorrowSleepEndTimestampGMT: z.string().nullable(),
      tomorrowSleepStartTimestampLocal: z.string().nullable(),
      tomorrowSleepEndTimestampLocal: z.string().nullable(),
      averageSpO2: z.unknown().optional(),
      lowestSpO2: z.unknown().optional(),
      lastSevenDaysAvgSpO2: z.unknown().optional(),
      latestSpO2: z.unknown().optional(),
      latestSpO2TimestampGMT: z.unknown().optional(),
      latestSpO2TimestampLocal: z.unknown().optional(),
      avgSleepSpO2: z.unknown().optional(),
      avgTomorrowSleepSpO2: z.unknown().optional(),
      spO2ValueDescriptorsDTOList: z.unknown().optional(),
      spO2SingleValues: z.unknown().optional(),
      continuousReadingDTOList: z.unknown().optional(),
      spO2HourlyAverages: z.unknown().optional(),
    })
    .nullable(),
  steps: z
    .array(
      z
        .looseObject({
          calendarDate: z.string().nullable(),
          totalSteps: z.number().nullable(),
          totalDistance: z.number().nullable(),
          stepGoal: z.number().nullable(),
        })
        .nullable(),
    )
    .nullable(),
  stress: z
    .looseObject({
      userProfilePK: z.number().nullable(),
      calendarDate: z.string().nullable(),
      startTimestampGMT: z.string().nullable(),
      endTimestampGMT: z.string().nullable(),
      startTimestampLocal: z.string().nullable(),
      endTimestampLocal: z.string().nullable(),
      maxStressLevel: z.number().nullable(),
      avgStressLevel: z.number().nullable(),
      stressChartValueOffset: z.number().nullable(),
      stressChartYAxisOrigin: z.number().nullable(),
      stressValueDescriptorsDTOList: z
        .array(
          z
            .looseObject({
              index: z.number().nullable(),
              key: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      stressValuesArray: z.array(z.array(z.number().nullable()).nullable()).nullable(),
      bodyBatteryValueDescriptorsDTOList: z
        .array(
          z
            .looseObject({
              bodyBatteryValueDescriptorIndex: z.number().nullable(),
              bodyBatteryValueDescriptorKey: z.string().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      bodyBatteryValuesArray: z.array(z.array(z.unknown()).nullable()).nullable(),
    })
    .nullable(),
  trainingPlans: z
    .looseObject({
      trainingPlanList: z.array(z.unknown()).nullable(),
      searchFilter: z
        .looseObject({
          ownerId: z.number().nullable(),
          trainingStatusList: z.array(z.unknown()).nullable(),
          start: z.number().nullable(),
          limit: z.number().nullable(),
          planKey: z.boolean().nullable(),
          ownerDisplayName: z.unknown().optional(),
          trainingLevels: z.unknown().optional(),
          trainingTypes: z.unknown().optional(),
          trainingSubTypes: z.unknown().optional(),
          trainingVersions: z.unknown().optional(),
          allowedPrivacyList: z.unknown().optional(),
          locale: z.unknown().optional(),
        })
        .nullable(),
    })
    .nullable(),
  trainingReadiness: z
    .array(
      z
        .looseObject({
          userProfilePK: z.number().nullable(),
          calendarDate: z.string().nullable(),
          timestamp: z.string().nullable(),
          timestampLocal: z.string().nullable(),
          deviceId: z.number().nullable(),
          level: z.string().nullable(),
          feedbackLong: z.string().nullable(),
          feedbackShort: z.string().nullable(),
          score: z.number().nullable(),
          sleepScore: z.number().nullable(),
          sleepScoreFactorPercent: z.number().nullable(),
          sleepScoreFactorFeedback: z.string().nullable(),
          recoveryTime: z.number().nullable(),
          recoveryTimeFactorPercent: z.number().nullable(),
          recoveryTimeFactorFeedback: z.string().nullable(),
          acwrFactorPercent: z.number().nullable(),
          acwrFactorFeedback: z.string().nullable(),
          acuteLoad: z.number().nullable(),
          stressHistoryFactorPercent: z.number().nullable(),
          stressHistoryFactorFeedback: z.string().nullable(),
          hrvFactorPercent: z.number().nullable(),
          hrvFactorFeedback: z.string().nullable(),
          hrvWeeklyAverage: z.number().nullable(),
          sleepHistoryFactorPercent: z.number().nullable(),
          sleepHistoryFactorFeedback: z.string().nullable(),
          validSleep: z.boolean().nullable(),
          primaryActivityTracker: z.boolean().nullable(),
          recoveryTimeChangePhrase: z.string().nullable(),
          inputContext: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
  trainingStatus: z
    .looseObject({
      mostRecentHeatAltitudeAcclimation: z
        .looseObject({
          requestUrl: z.string().nullable(),
          statusCode: z.number().nullable(),
          headers: z.looseObject({}).nullable(),
          payload: z
            .looseObject({
              calendarDate: z.string().nullable(),
              altitudeAcclimationDate: z.string().nullable(),
              previousAltitudeAcclimationDate: z.string().nullable(),
              heatAcclimationDate: z.string().nullable(),
              previousHeatAcclimationDate: z.string().nullable(),
              altitudeAcclimation: z.number().nullable(),
              previousAltitudeAcclimation: z.number().nullable(),
              heatAcclimationPercentage: z.number().nullable(),
              previousHeatAcclimationPercentage: z.number().nullable(),
              heatTrend: z.string().nullable(),
              currentAltitude: z.number().nullable(),
              previousAltitude: z.number().nullable(),
              acclimationPercentage: z.number().nullable(),
              previousAcclimationPercentage: z.number().nullable(),
              altitudeAcclimationLocalTimestamp: z.string().nullable(),
              altitudeTrend: z.unknown().optional(),
            })
            .nullable(),
          successful: z.boolean().nullable(),
          errorMessage: z.unknown().optional(),
        })
        .nullable(),
      mostRecentVO2Max: z
        .looseObject({
          requestUrl: z.string().nullable(),
          statusCode: z.number().nullable(),
          headers: z.looseObject({}).nullable(),
          payload: z
            .looseObject({
              userId: z.number().nullable(),
              generic: z.looseObject({}).nullable(),
              heatAltitudeAcclimation: z.looseObject({}).nullable(),
              cycling: z.unknown().optional(),
            })
            .nullable(),
          successful: z.boolean().nullable(),
          errorMessage: z.unknown().optional(),
        })
        .nullable(),
      mostRecentTrainingLoadBalance: z
        .looseObject({
          requestUrl: z.string().nullable(),
          statusCode: z.number().nullable(),
          headers: z.looseObject({}).nullable(),
          payload: z
            .looseObject({
              userId: z.number().nullable(),
              metricsTrainingLoadBalanceDTOMap: z.looseObject({}).nullable(),
              recordedDevices: z.array(z.unknown()).nullable(),
            })
            .nullable(),
          successful: z.boolean().nullable(),
          errorMessage: z.unknown().optional(),
        })
        .nullable(),
      mostRecentTrainingStatus: z
        .looseObject({
          requestUrl: z.string().nullable(),
          statusCode: z.number().nullable(),
          headers: z.looseObject({}).nullable(),
          payload: z
            .looseObject({
              userId: z.number().nullable(),
              latestTrainingStatusData: z.looseObject({}).nullable(),
              recordedDevices: z.array(z.unknown()).nullable(),
              showSelector: z.boolean().nullable(),
              lastPrimarySyncDate: z.string().nullable(),
            })
            .nullable(),
          successful: z.boolean().nullable(),
          errorMessage: z.unknown().optional(),
        })
        .nullable(),
    })
    .nullable(),
  trainingStatusRange: z
    .looseObject({
      vo2MaxWeeklyStatistics: z
        .looseObject({
          requestUrl: z.string().nullable(),
          statusCode: z.number().nullable(),
          headers: z.looseObject({}).nullable(),
          payload: z
            .looseObject({
              userProfileId: z.number().nullable(),
              statisticsStartDate: z.string().nullable(),
              statisticsEndDate: z.string().nullable(),
              allMetrics: z.looseObject({}).nullable(),
              groupedMetrics: z.unknown().optional(),
            })
            .nullable(),
          successful: z.boolean().nullable(),
          errorMessage: z.unknown().optional(),
        })
        .nullable(),
      weeklyTrainingStatus: z
        .looseObject({
          requestUrl: z.string().nullable(),
          statusCode: z.number().nullable(),
          headers: z.looseObject({}).nullable(),
          payload: z
            .looseObject({
              userId: z.number().nullable(),
              fromCalendarDate: z.string().nullable(),
              toCalendarDate: z.string().nullable(),
              showSelector: z.boolean().nullable(),
              recordedDevices: z.array(z.unknown()).nullable(),
              reportData: z.looseObject({}).nullable(),
            })
            .nullable(),
          successful: z.boolean().nullable(),
          errorMessage: z.unknown().optional(),
        })
        .nullable(),
    })
    .nullable(),
  userProfile: z
    .looseObject({
      id: z.number().nullable(),
      profileId: z.number().nullable(),
      garminGUID: z.string().nullable(),
      displayName: z.string().nullable(),
      fullName: z.string().nullable(),
      userName: z.string().nullable(),
      profileImageType: z.string().nullable(),
      profileImageUrlLarge: z.string().nullable(),
      profileImageUrlMedium: z.string().nullable(),
      profileImageUrlSmall: z.string().nullable(),
      hasPremiumSocialIcon: z.boolean().nullable(),
      location: z.string().nullable(),
      favoriteActivityTypes: z.array(z.string().nullable()).nullable(),
      runningTrainingSpeed: z.number().nullable(),
      cyclingTrainingSpeed: z.number().nullable(),
      favoriteCyclingActivityTypes: z.array(z.unknown()).nullable(),
      cyclingMaxAvgPower: z.number().nullable(),
      swimmingTrainingSpeed: z.number().nullable(),
      profileVisibility: z.string().nullable(),
      activityStartVisibility: z.string().nullable(),
      activityMapVisibility: z.string().nullable(),
      courseVisibility: z.string().nullable(),
      activityHeartRateVisibility: z.string().nullable(),
      activityPowerVisibility: z.string().nullable(),
      badgeVisibility: z.string().nullable(),
      showAge: z.boolean().nullable(),
      showWeight: z.boolean().nullable(),
      showHeight: z.boolean().nullable(),
      showWeightClass: z.boolean().nullable(),
      showAgeRange: z.boolean().nullable(),
      showGender: z.boolean().nullable(),
      showActivityClass: z.boolean().nullable(),
      showVO2Max: z.boolean().nullable(),
      showPersonalRecords: z.boolean().nullable(),
      showLast12Months: z.boolean().nullable(),
      showLifetimeTotals: z.boolean().nullable(),
      showUpcomingEvents: z.boolean().nullable(),
      showRecentFavorites: z.boolean().nullable(),
      showRecentDevice: z.boolean().nullable(),
      showRecentGear: z.boolean().nullable(),
      showBadges: z.boolean().nullable(),
      userRoles: z.array(z.string().nullable()).nullable(),
      nameApproved: z.boolean().nullable(),
      userProfileFullName: z.string().nullable(),
      makeGolfScorecardsPrivate: z.boolean().nullable(),
      allowGolfLiveScoring: z.boolean().nullable(),
      allowGolfScoringByConnections: z.boolean().nullable(),
      userLevel: z.number().nullable(),
      userPoint: z.number().nullable(),
      levelUpdateDate: z.string().nullable(),
      levelIsViewed: z.boolean().nullable(),
      levelPointThreshold: z.number().nullable(),
      userPointOffset: z.number().nullable(),
      userPro: z.boolean().nullable(),
      facebookUrl: z.unknown().optional(),
      twitterUrl: z.unknown().optional(),
      personalWebsite: z.unknown().optional(),
      motivation: z.unknown().optional(),
      bio: z.unknown().optional(),
      primaryActivity: z.unknown().optional(),
      cyclingClassification: z.unknown().optional(),
      otherActivity: z.unknown().optional(),
      otherPrimaryActivity: z.unknown().optional(),
      otherMotivation: z.unknown().optional(),
    })
    .nullable(),
  userSettings: z
    .looseObject({
      id: z.number().nullable(),
      userData: z
        .looseObject({
          gender: z.string().nullable(),
          weight: z.number().nullable(),
          height: z.number().nullable(),
          timeFormat: z.string().nullable(),
          birthDate: z.string().nullable(),
          measurementSystem: z.string().nullable(),
          handedness: z.string().nullable(),
          powerFormat: z
            .looseObject({
              formatId: z.number().nullable(),
              formatKey: z.string().nullable(),
              minFraction: z.number().nullable(),
              maxFraction: z.number().nullable(),
              groupingUsed: z.boolean().nullable(),
              displayFormat: z.unknown().optional(),
            })
            .nullable(),
          heartRateFormat: z
            .looseObject({
              formatId: z.number().nullable(),
              formatKey: z.string().nullable(),
              minFraction: z.number().nullable(),
              maxFraction: z.number().nullable(),
              groupingUsed: z.boolean().nullable(),
              displayFormat: z.unknown().optional(),
            })
            .nullable(),
          firstDayOfWeek: z
            .looseObject({
              dayId: z.number().nullable(),
              dayName: z.string().nullable(),
              sortOrder: z.number().nullable(),
              isPossibleFirstDay: z.boolean().nullable(),
            })
            .nullable(),
          vo2MaxRunning: z.number().nullable(),
          lactateThresholdHeartRate: z.number().nullable(),
          intensityMinutesCalcMethod: z.string().nullable(),
          moderateIntensityMinutesHrZone: z.number().nullable(),
          vigorousIntensityMinutesHrZone: z.number().nullable(),
          hydrationMeasurementUnit: z.string().nullable(),
          hydrationContainers: z.array(z.unknown()).nullable(),
          hydrationAutoGoalEnabled: z.boolean().nullable(),
          thresholdHeartRateAutoDetected: z.boolean().nullable(),
          ftpAutoDetected: z.boolean().nullable(),
          weatherLocation: z
            .looseObject({
              useFixedLocation: z.boolean().nullable(),
              latitude: z.unknown().optional(),
              longitude: z.unknown().optional(),
              locationName: z.unknown().optional(),
              isoCountryCode: z.unknown().optional(),
              postalCode: z.unknown().optional(),
            })
            .nullable(),
          golfDistanceUnit: z.string().nullable(),
          availableTrainingDays: z.array(z.string().nullable()).nullable(),
          preferredLongTrainingDays: z.array(z.string().nullable()).nullable(),
          activityLevel: z.unknown().optional(),
          vo2MaxCycling: z.unknown().optional(),
          lactateThresholdSpeed: z.unknown().optional(),
          diveNumber: z.unknown().optional(),
          firstbeatMaxStressScore: z.unknown().optional(),
          firstbeatCyclingLtTimestamp: z.unknown().optional(),
          firstbeatRunningLtTimestamp: z.unknown().optional(),
          trainingStatusPausedDate: z.unknown().optional(),
          golfElevationUnit: z.unknown().optional(),
          golfSpeedUnit: z.unknown().optional(),
          externalBottomTime: z.unknown().optional(),
          virtualCaddieDataSource: z.unknown().optional(),
          numberDivesAutomatically: z.unknown().optional(),
          firstbeatRowingLtTimestamp: z.unknown().optional(),
          lactateThresholdRowingPace: z.unknown().optional(),
          lactateThresholdHeartRateRowing: z.unknown().optional(),
          lactateThresholdHeartRateCycling: z.unknown().optional(),
          wtrPrimaryActivityType: z.unknown().optional(),
        })
        .nullable(),
      userSleep: z
        .looseObject({
          sleepTime: z.number().nullable(),
          defaultSleepTime: z.boolean().nullable(),
          wakeTime: z.number().nullable(),
          defaultWakeTime: z.boolean().nullable(),
        })
        .nullable(),
      userSleepWindows: z
        .array(
          z
            .looseObject({
              sleepWindowFrequency: z.string().nullable(),
              startSleepTimeSecondsFromMidnight: z.number().nullable(),
              endSleepTimeSecondsFromMidnight: z.number().nullable(),
            })
            .nullable(),
        )
        .nullable(),
      connectDate: z.unknown().optional(),
      sourceType: z.unknown().optional(),
    })
    .nullable(),
  userSummary: z
    .looseObject({
      userProfileId: z.number().nullable(),
      totalKilocalories: z.number().nullable(),
      activeKilocalories: z.number().nullable(),
      bmrKilocalories: z.number().nullable(),
      wellnessKilocalories: z.number().nullable(),
      totalSteps: z.number().nullable(),
      totalDistanceMeters: z.number().nullable(),
      wellnessDistanceMeters: z.number().nullable(),
      wellnessActiveKilocalories: z.number().nullable(),
      netRemainingKilocalories: z.number().nullable(),
      userDailySummaryId: z.number().nullable(),
      calendarDate: z.string().nullable(),
      rule: z
        .looseObject({
          typeId: z.number().nullable(),
          typeKey: z.string().nullable(),
        })
        .nullable(),
      uuid: z.string().nullable(),
      dailyStepGoal: z.number().nullable(),
      wellnessStartTimeGmt: z.string().nullable(),
      wellnessStartTimeLocal: z.string().nullable(),
      wellnessEndTimeGmt: z.string().nullable(),
      wellnessEndTimeLocal: z.string().nullable(),
      durationInMilliseconds: z.number().nullable(),
      highlyActiveSeconds: z.number().nullable(),
      activeSeconds: z.number().nullable(),
      sedentarySeconds: z.number().nullable(),
      sleepingSeconds: z.number().nullable(),
      includesWellnessData: z.boolean().nullable(),
      includesActivityData: z.boolean().nullable(),
      includesCalorieConsumedData: z.boolean().nullable(),
      privacyProtected: z.boolean().nullable(),
      moderateIntensityMinutes: z.number().nullable(),
      vigorousIntensityMinutes: z.number().nullable(),
      floorsAscendedInMeters: z.number().nullable(),
      floorsDescendedInMeters: z.number().nullable(),
      floorsAscended: z.number().nullable(),
      floorsDescended: z.number().nullable(),
      intensityMinutesGoal: z.number().nullable(),
      userFloorsAscendedGoal: z.number().nullable(),
      minHeartRate: z.number().nullable(),
      maxHeartRate: z.number().nullable(),
      restingHeartRate: z.number().nullable(),
      lastSevenDaysAvgRestingHeartRate: z.number().nullable(),
      source: z.string().nullable(),
      averageStressLevel: z.number().nullable(),
      maxStressLevel: z.number().nullable(),
      stressDuration: z.number().nullable(),
      restStressDuration: z.number().nullable(),
      activityStressDuration: z.number().nullable(),
      uncategorizedStressDuration: z.number().nullable(),
      totalStressDuration: z.number().nullable(),
      lowStressDuration: z.number().nullable(),
      mediumStressDuration: z.number().nullable(),
      highStressDuration: z.number().nullable(),
      stressPercentage: z.number().nullable(),
      restStressPercentage: z.number().nullable(),
      activityStressPercentage: z.number().nullable(),
      uncategorizedStressPercentage: z.number().nullable(),
      lowStressPercentage: z.number().nullable(),
      mediumStressPercentage: z.number().nullable(),
      highStressPercentage: z.number().nullable(),
      stressQualifier: z.string().nullable(),
      measurableAwakeDuration: z.number().nullable(),
      measurableAsleepDuration: z.number().nullable(),
      minAvgHeartRate: z.number().nullable(),
      maxAvgHeartRate: z.number().nullable(),
      bodyBatteryChargedValue: z.number().nullable(),
      bodyBatteryDrainedValue: z.number().nullable(),
      bodyBatteryHighestValue: z.number().nullable(),
      bodyBatteryLowestValue: z.number().nullable(),
      bodyBatteryMostRecentValue: z.number().nullable(),
      bodyBatteryDuringSleep: z.number().nullable(),
      bodyBatteryAtWakeTime: z.number().nullable(),
      bodyBatteryVersion: z.number().nullable(),
      avgWakingRespirationValue: z.number().nullable(),
      highestRespirationValue: z.number().nullable(),
      lowestRespirationValue: z.number().nullable(),
      latestRespirationValue: z.number().nullable(),
      latestRespirationTimeGMT: z.string().nullable(),
      respirationAlgorithmVersion: z.number().nullable(),
      burnedKilocalories: z.unknown().optional(),
      consumedKilocalories: z.unknown().optional(),
      remainingKilocalories: z.unknown().optional(),
      netCalorieGoal: z.unknown().optional(),
      wellnessDescription: z.unknown().optional(),
      lastSyncTimestampGMT: z.unknown().optional(),
      abnormalHeartRateAlertsCount: z.unknown().optional(),
      averageSpo2: z.unknown().optional(),
      lowestSpo2: z.unknown().optional(),
      latestSpo2: z.unknown().optional(),
      latestSpo2ReadingTimeGmt: z.unknown().optional(),
      latestSpo2ReadingTimeLocal: z.unknown().optional(),
      averageMonitoringEnvironmentAltitude: z.unknown().optional(),
      restingCaloriesFromActivity: z.unknown().optional(),
    })
    .nullable(),
  vo2Max: z
    .array(
      z
        .looseObject({
          userId: z.number().nullable(),
          generic: z
            .looseObject({
              calendarDate: z.string().nullable(),
              vo2MaxPreciseValue: z.number().nullable(),
              vo2MaxValue: z.number().nullable(),
              maxMetCategory: z.number().nullable(),
              fitnessAge: z.unknown().optional(),
              fitnessAgeDescription: z.unknown().optional(),
            })
            .nullable(),
          heatAltitudeAcclimation: z
            .looseObject({
              calendarDate: z.string().nullable(),
              altitudeAcclimationDate: z.string().nullable(),
              previousAltitudeAcclimationDate: z.string().nullable(),
              heatAcclimationDate: z.string().nullable(),
              previousHeatAcclimationDate: z.string().nullable(),
              altitudeAcclimation: z.number().nullable(),
              previousAltitudeAcclimation: z.number().nullable(),
              heatAcclimationPercentage: z.number().nullable(),
              previousHeatAcclimationPercentage: z.number().nullable(),
              currentAltitude: z.number().nullable(),
              previousAltitude: z.number().nullable(),
              acclimationPercentage: z.number().nullable(),
              previousAcclimationPercentage: z.number().nullable(),
              altitudeAcclimationLocalTimestamp: z.string().nullable(),
              heatTrend: z.string().nullable().optional(),
              altitudeTrend: z.unknown().optional(),
            })
            .nullable(),
          cycling: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
  weeklyIntensityMinutes: z
    .array(
      z
        .looseObject({
          calendarDate: z.string().nullable(),
          weeklyGoal: z.number().nullable(),
          moderateValue: z.number().nullable(),
          vigorousValue: z.number().nullable(),
        })
        .nullable(),
    )
    .nullable(),
  weeklySteps: z
    .array(
      z
        .looseObject({
          calendarDate: z.string().nullable(),
          values: z
            .looseObject({
              totalSteps: z.number().nullable(),
              averageSteps: z.number().nullable(),
              wellnessDataDaysCount: z.number().nullable(),
              averageDistance: z.number().nullable(),
              totalDistance: z.number().nullable(),
            })
            .nullable(),
        })
        .nullable(),
    )
    .nullable(),
  weeklyStress: z
    .array(
      z
        .looseObject({
          calendarDate: z.string().nullable(),
          value: z.number().nullable(),
        })
        .nullable(),
    )
    .nullable(),
  weighIns: z
    .looseObject({
      dailyWeightSummaries: z.array(z.unknown()).nullable(),
      totalAverage: z
        .looseObject({
          from: z.number().nullable(),
          until: z.number().nullable(),
          weight: z.unknown().optional(),
          bmi: z.unknown().optional(),
          bodyFat: z.unknown().optional(),
          bodyWater: z.unknown().optional(),
          boneMass: z.unknown().optional(),
          muscleMass: z.unknown().optional(),
          physiqueRating: z.unknown().optional(),
          visceralFat: z.unknown().optional(),
          metabolicAge: z.unknown().optional(),
        })
        .nullable(),
      previousDateWeight: z
        .looseObject({
          samplePk: z.number().nullable(),
          date: z.number().nullable(),
          calendarDate: z.string().nullable(),
          weight: z.number().nullable(),
          sourceType: z.string().nullable(),
          timestampGMT: z.number().nullable(),
          weightDelta: z.number().nullable(),
          bmi: z.unknown().optional(),
          bodyFat: z.unknown().optional(),
          bodyWater: z.unknown().optional(),
          boneMass: z.unknown().optional(),
          muscleMass: z.unknown().optional(),
          physiqueRating: z.unknown().optional(),
          visceralFat: z.unknown().optional(),
          metabolicAge: z.unknown().optional(),
        })
        .nullable(),
      nextDateWeight: z.unknown().optional(),
    })
    .nullable(),
  workout: z
    .looseObject({
      workoutId: z.number().nullable(),
      ownerId: z.number().nullable(),
      workoutName: z.string().nullable(),
      description: z.string().nullable(),
      updatedDate: z.string().nullable(),
      createdDate: z.string().nullable(),
      sportType: z
        .looseObject({
          sportTypeId: z.number().nullable(),
          sportTypeKey: z.string().nullable(),
          displayOrder: z.number().nullable(),
        })
        .nullable(),
      author: z
        .looseObject({
          userProfilePk: z.number().nullable(),
          displayName: z.string().nullable(),
          fullName: z.string().nullable(),
          userPro: z.boolean().nullable(),
          vivokidUser: z.boolean().nullable(),
          profileImgNameLarge: z.unknown().optional(),
          profileImgNameMedium: z.unknown().optional(),
          profileImgNameSmall: z.unknown().optional(),
        })
        .nullable(),
      estimatedDurationInSecs: z.number().nullable(),
      estimatedDistanceInMeters: z.number().nullable(),
      workoutSegments: z
        .array(
          z
            .looseObject({
              segmentOrder: z.number().nullable(),
              sportType: z.looseObject({}).nullable(),
              workoutSteps: z.array(z.unknown()).nullable(),
              poolLengthUnit: z.unknown().optional(),
              poolLength: z.unknown().optional(),
              avgTrainingSpeed: z.unknown().optional(),
              estimatedDurationInSecs: z.unknown().optional(),
              estimatedDistanceInMeters: z.unknown().optional(),
              estimatedDistanceUnit: z.unknown().optional(),
              estimateType: z.unknown().optional(),
              description: z.unknown().optional(),
            })
            .nullable(),
        )
        .nullable(),
      avgTrainingSpeed: z.number().nullable(),
      estimateType: z.string().nullable(),
      estimatedDistanceUnit: z
        .looseObject({
          unitId: z.number().nullable(),
          unitKey: z.string().nullable(),
          factor: z.number().nullable(),
        })
        .nullable(),
      workoutThumbnailUrl: z.string().nullable(),
      shared: z.boolean().nullable(),
      subSportType: z.unknown().optional(),
      trainingPlanId: z.unknown().optional(),
      sharedWithUsers: z.unknown().optional(),
      poolLength: z.unknown().optional(),
      poolLengthUnit: z.unknown().optional(),
      locale: z.unknown().optional(),
      workoutProvider: z.unknown().optional(),
      workoutSourceId: z.unknown().optional(),
      uploadTimestamp: z.unknown().optional(),
      atpPlanId: z.unknown().optional(),
      consumer: z.unknown().optional(),
      consumerName: z.unknown().optional(),
      consumerImageURL: z.unknown().optional(),
      consumerWebsiteURL: z.unknown().optional(),
      workoutNameI18nKey: z.unknown().optional(),
      descriptionI18nKey: z.unknown().optional(),
      isSessionTransitionEnabled: z.unknown().optional(),
    })
    .nullable(),
  workouts: z
    .array(
      z
        .looseObject({
          workoutId: z.number().nullable(),
          ownerId: z.number().nullable(),
          workoutName: z.string().nullable(),
          description: z.string().nullable(),
          updateDate: z.string().nullable(),
          createdDate: z.string().nullable(),
          sportType: z
            .looseObject({
              sportTypeId: z.number().nullable(),
              sportTypeKey: z.string().nullable(),
              displayOrder: z.number().nullable(),
            })
            .nullable(),
          author: z
            .looseObject({
              userPro: z.boolean().nullable(),
              vivokidUser: z.boolean().nullable(),
              userProfilePk: z.unknown().optional(),
              displayName: z.unknown().optional(),
              fullName: z.unknown().optional(),
              profileImgNameLarge: z.unknown().optional(),
              profileImgNameMedium: z.unknown().optional(),
              profileImgNameSmall: z.unknown().optional(),
            })
            .nullable(),
          estimatedDurationInSecs: z.number().nullable(),
          estimatedDistanceInMeters: z.number().nullable(),
          estimateType: z.string().nullable(),
          estimatedDistanceUnit: z
            .looseObject({
              unitId: z.number().nullable(),
              unitKey: z.string().nullable(),
              factor: z.number().nullable(),
            })
            .nullable(),
          poolLength: z.number().nullable(),
          poolLengthUnit: z
            .looseObject({
              unitId: z.number().nullable(),
              unitKey: z.string().nullable(),
              factor: z.number().nullable(),
            })
            .nullable(),
          workoutThumbnailUrl: z.string().nullable(),
          shared: z.boolean().nullable(),
          estimated: z.boolean().nullable(),
          trainingPlanId: z.unknown().optional(),
          workoutProvider: z.unknown().optional(),
          workoutSourceId: z.unknown().optional(),
          consumer: z.unknown().optional(),
          atpPlanId: z.unknown().optional(),
          workoutNameI18nKey: z.unknown().optional(),
          descriptionI18nKey: z.unknown().optional(),
        })
        .nullable(),
    )
    .nullable(),
};
