/**
 * Infer zod response schemas from raw captures in .live-capture/ and write
 * tests/schemas.ts. Run after `npm run test:live`: npm run schemas:generate
 *
 * A key is required when it is present and non-null in every sample (Garmin
 * omits keys that don't apply, e.g. elevation on treadmill runs); every value
 * may be null, since Garmin returns nulls on days without data.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Exchange } from "./sanitize.ts";

const RAW = join(import.meta.dirname, "../../.live-capture");
const OUT = join(import.meta.dirname, "../schemas.ts");
const MAX_DEPTH = 4;
const WIDE_OBJECT = 200; // device records carry 300+ capability flags
const WIDE_KEEP = 20;

const ident = (k: string) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
const isObj = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

function infer(samples: unknown[], depth: number): string {
  const vals = samples.filter((v) => v !== null && v !== undefined);
  if (vals.length === 0) return "z.unknown()";
  if (vals.every((v) => typeof v === "boolean")) return "z.boolean().nullable()";
  if (vals.every((v) => typeof v === "number")) return "z.number().nullable()";
  if (vals.every((v) => typeof v === "string")) return "z.string().nullable()";
  if (vals.every(Array.isArray)) {
    const elems = (vals as unknown[][]).flat();
    if (elems.length === 0 || depth >= MAX_DEPTH) return "z.array(z.unknown()).nullable()";
    return `z.array(${infer(elems, depth + 1)}).nullable()`;
  }
  if (vals.every(isObj)) {
    if (depth >= MAX_DEPTH) return "z.looseObject({}).nullable()";
    const objs = vals as Record<string, unknown>[];
    const keys = [...new Set(objs.flatMap((o) => Object.keys(o)))];
    const required = keys.filter((k) => objs.every((o) => o[k] !== null && o[k] !== undefined));
    const ordered = [...required, ...keys.filter((k) => !required.includes(k))];
    const chosen = ordered.length > WIDE_OBJECT ? ordered.slice(0, WIDE_KEEP) : ordered;
    const pad = "  ".repeat(depth + 1);
    const fields = chosen.map((k) => {
      const t = infer(
        objs.map((o) => o[k]),
        depth + 1,
      );
      return `${pad}${ident(k)}: ${t}${required.includes(k) ? "" : ".optional()"},`;
    });
    return `z.looseObject({\n${fields.join("\n")}\n${"  ".repeat(depth)}}).nullable()`;
  }
  return "z.unknown()";
}

const lines = [
  'import { z } from "zod";',
  "",
  "// Generated by tests/live/generate-schemas.ts from a live capture. Required =",
  "// present and non-null in every sample; all values may be null (Garmin returns",
  "// nulls on days without data).",
  "",
  "export const responseSchemas: Record<string, z.ZodType> = {",
];
for (const file of readdirSync(RAW).sort()) {
  if (!file.endsWith(".json") || file.startsWith("_")) continue;
  const name = file.slice(0, -5);
  const exchanges: Exchange[] = JSON.parse(readFileSync(join(RAW, file), "utf-8"));
  // Some methods look up the profile first; the endpoint's own response is last
  const last = exchanges.at(-1);
  if (!last) continue;
  if (last.status === 204) {
    lines.push(`  ${name}: z.unknown(), // 204 No Content when there is no data`);
  } else if (last.status < 300) {
    lines.push(`  ${name}: ${infer([last.body], 1)},`);
  }
}
lines.push("};", "");
writeFileSync(OUT, lines.join("\n"));
console.log(`wrote ${OUT}`);
